language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
services:
  - postgresql

sudo: false
dist: trusty

env:
  global:
    - PG_CONNECTION_STRING=postgres://postgres:postgres@localhost:5432/my_test_db
    - TIMEOUT=15000
install:
  - npm install
test:
  - npm test
after_success:
  - npm run coverage
deploy:
  provider: script
  script_cleanup: true
  script:
    - npx semantic-release